version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: airport_postgres
    restart: always
    environment:
      POSTGRES_DB: airportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - airport_pgdata:/var/lib/postgresql/data

volumes:
  airport_pgdata: